services:
  - type: web
    name: flask-practica06
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DATABASE_URL
        value: "postgresql://flask_db_f0of_user:0A6uRzT5eHl6v8rVfQoXmC1vW2YqN3zZ@dpg-cvb7e80gph6c738o25ag-a/flask_db_f0of"
